bloom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/urls.py
from django.urls import path

from . import views


urlpatterns = [
 path('', views.home),
 path('second/', views.secondpage),
 path('seblak-bloom/', views.viewSeblak),
 path('bloom-raw-honey/', views.viewMadu),
 path('franchise/', views.viewFranchise),
 path('daftar-outlet/', views.viewLokasiOutlet),
 path('tentang-kami/', views.viewTentang)
]

web/models.py
from django.db import models

# Create your models here.

class Kota(models.Model):
    CHOICES = [('Tersedia', 'Tersedia'), ('Penuh', 'Penuh')]
    nama_kota = models.TextField()
    status = models.TextField(choices=CHOICES, default = 'Tersedia')
    def __str__(self):
        return self.nama_kota


class Outlet(models.Model):
    kota = models.ForeignKey(Kota, on_delete=models.CASCADE)
    alamat = models.TextField()

web/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def home(request):
    return render(request, 'index.html')

def secondpage(request):
    return render(request, 'inner-page.html')    


def viewSeblak(request):
    return render(request, 'seblak.html')


def viewMadu(request):
    return render(request, 'madu.html')


def viewFranchise(request):
    return render(request, 'inner-page.html')


def viewLokasiOutlet(request):
    kota = Kota.objects.all()
    dict = {
        'kotas':kota
    }
    return render(request, 'lokasi_outlet.html', dict)


def viewTentang(request):
    return render(request, 'tentang-kami.html')

web/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Home | Bloom Indonesia</title>
  <meta content="Hai, selamat datang di website resmi Bloom Indonesia! Temukan mengenai info produk serta kemitraan dengan Bloom Indonesia disini." name="description">
  <meta content="bloom indonesia, franchise seblak, seblak bloom" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href=" {% static "assets/vendor/bootstrap/css/bootstrap.min.css" %}"  rel="stylesheet">
  <link href=" {% static "assets/vendor/icofont/icofont.min.css" %}" rel="stylesheet">
  <link href=" {% static "assets/vendor/boxicons/css/boxicons.min.css" %}" rel="stylesheet">
  <link href=" {% static "assets/vendor/venobox/venobox.css" %}" rel="stylesheet">
  <link href=" {% static "assets/vendor/owl.carousel/assets/owl.carousel.min.css" %}" rel="stylesheet">
  <link href=" {% static "assets/vendor/aos/aos.css" %}" rel="stylesheet">

  <link href=" {% static "assets/css/style.css" %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container-fluid d-flex">

      <div class="logo mr-auto">
        <!--<h1 class="text-light"><a href="index.html"><span>Ninestars</span></a></h1>-->
        <!-- Uncomment below if you prefer to use an image logo -->
         <a href="/"><img src=" {% static "logseblak.png"%}" alt="" class="img-fluid"></a>
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="/">Home</a></li>
          <li><a href="#about">Tentang Kami</a></li>
          <li><a href="#produk">Produk</a></li>
          <!--
          <li class="drop-down"><a href="">Drop Down</a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="drop-down"><a href="#">Drop Down 2</a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
              <li><a href="#">Drop Down 5</a></li>
            </ul>
          </li> -->
          <li><a href="#contact">Kontak</a></li>
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1">
          <div class="flex-center-vertically">
          <h1 class="color-white">8 tahun hadir untuk keluarga Indonesia</h1>
          <h2 class="color-white">Bloom terus berinovasi dan memberikan yang terbaik untuk Indonesia</h2>
        </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 hero-img">
          <!--<img src="assets/img/hero-img.svg" class="img-fluid animated" alt="">-->
          <img src=" {% static "logseblak2.png"%}" width=100% alt="" style="margin: auto;    
    display: block;">
        </div>
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">

        <div class="row justify-content-between">
          <div class="col-lg-5 d-flex align-items-center justify-content-center about-img">
            <img src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=751&q=80" style="border-radius: 20px;" class="img-fluid" alt="" data-aos="zoom-in">
          </div>
          <div class="col-lg-6 pt-5 pt-lg-0">
            <h3 data-aos="fade-up">Siapa kami?</h3>
            <p data-aos="fade-up" data-aos-delay="100">
              Bloom adalah perusahaan mandiri yang sudah melayani Indonesia di banyak kota selama 8 tahun.
            </p>
            <a  class="btn btn-primary scrollto" href="/tentang-kami" style="background: #eb5d1e;
    color: #fff;
    border-radius: 50px; border-color:transparent">Selengkapnya</a>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->

    <!-- ======= Services Section ======= -->
    <section id="produk" class="services section-bg">
      <div class="container">

        <div class="section-title" data-aos="fade-up">
          <h2>Kreasi Kami</h2>
          <p>Made with ❤️ by Bloom Indonesia</p>
        </div>

        <div class="row mx-auto">
          <div class="col-md-12">
            <div class="card rounded-lg" style="overflow: hidden; position: relative;">
              <div class="dis-seblak"></div>
              <div class="abs text-center ">
              <h2 class="title color-white text-center" style="font-size: 2rem!important;">Bloom Sundanese Seblak</h2>
              <a class="btn btn-primary" style="background: #eb5d1e;
    color: #fff;
    border-radius: 50px; border-color:transparent" href="/seblak-bloom">Selengkapnya</a>
    </div>
            </div>
</div>
         

        </div>
        </div>  

    </section><!-- End Services Section -->

    

    <!-- ======= Contact Us Section ======= -->
    <section id="contact" class="contact">
      <div class="container">

        <div class="section-title" data-aos="fade-up">
          <h2>Kontak Kami</h2>
          <p>Anda bisa menghubungi kami disini</p>
        </div>

        <div class="row">

          <div class="col d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
            <div class="info">
              <div class="address">
                <i class="icofont-google-map"></i>
                <h4>Lokasi:</h4>
                <p>Perum Ketapang Indah D3 No. 74, Jalan Suparjo Rustam, Dusun III, Sokaraja Kulon, Kec. Banyumas, Kabupaten Banyumas, Jawa Tengah 53181, Indonesia</p>
              </div>

              <div class="email">
                <i class="icofont-envelope"></i>
                <h4>Email:</h4>
                <p>bloomindonesia@yahoo.co.id</p>
              </div>

              <div class="phone">
                <i class="icofont-phone"></i>
                <h4>Telepon:</h4>
                <p>+6281225570100</p>
              </div>

          
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3956.2159711571962!2d109.27040171461265!3d-7.441340294631573!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e6566ffffffffdf%3A0xaed20eed987dd29e!2sBloom%20Headquarter!5e0!3m2!1sen!2sus!4v1603532804361!5m2!1sen!2sus" frameborder="0" style="border:0; width: 100%; height: 290px;" allowfullscreen aria-hidden="false" tabindex="0"></iframe>
            </div>

          </div>
<!-- 
          <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="200">
            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="name">Nama</label>
                  <input type="text" name="name" class="form-control" id="name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                  <div class="validate"></div>
                </div>
                <div class="form-group col-md-6">
                  <label for="name">Email</label>
                  <input type="email" class="form-control" name="email" id="email" data-rule="email" data-msg="Please enter a valid email" />
                  <div class="validate"></div>
                </div>
              </div>
              <div class="form-group">
                <label for="name">Subject</label>
                <input type="text" class="form-control" name="subject" id="subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                <div class="validate"></div>
              </div>
              <div class="form-group">
                <label for="name">Message</label>
                <textarea class="form-control" name="message" rows="10" data-rule="required" data-msg="Please write something for us"></textarea>
                <div class="validate"></div>
              </div>
              <div class="mb-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>
          </div> -->

        </div>

      </div>
    </section><!-- End Contact Us Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact" data-aos="fade-up" data-aos-delay="100">
              <img src="logseblak.png" alt="" width="50%" class="img-fluid">
              <h3>Bloom Indonesia</h3>
           
            <p>
              Perum Ketapang Indah D3 No. 74, Jalan Suparjo Rustam, Dusun III, Sokaraja Kulon, Kec. Banyumas, Kabupaten Banyumas, Jawa Tengah 53181, Indonesia
               <br>
              <strong>Telepon:</strong> <a href="tel:+6281225570100">+6281225570100</a><br>
              <strong>Email:</strong> bloomindonesia@yahoo.co.id<br>
            </p>
          </div>


          <div class="col-lg-3 col-md-6 footer-links" data-aos="fade-up" data-aos-delay="400">
            <h4>Our Social Networks</h4>
            <p>Temukan kami di platform lainnya</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright 2020,<strong><span> Bloom Indonesia</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
      
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src=" {% static "assets/vendor/jquery/jquery.min.js"%}"></script>
  <script src=" {% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js"%}"></script>
  <script src=" {% static "assets/vendor/jquery.easing/jquery.easing.min.js"%}"></script>
  <script src=" {% static "assets/vendor/php-email-form/validate.js"%}"></script>
  <script src=" {% static "assets/vendor/isotope-layout/isotope.pkgd.min.js"%}"></script>
  <script src=" {% static "assets/vendor/venobox/venobox.min.js"%}"></script>
  <script src=" {% static "assets/vendor/owl.carousel/owl.carousel.min.js"%}"></script>
  <script src=" {% static "assets/vendor/aos/aos.js"%}"></script>

  <!-- Template Main JS File -->
  <script src=" {% static "assets/js/main.js" %}"></script>

</body>

</html>

web/templates/lokasi_outlet.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Lokasi Outlet | Bloom Indonesia</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href=" {% static "assets/img/favicon.png" %}" rel="icon">
  <link href=" {% static "assets/img/apple-touch-icon.png" %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href=" {% static "assets/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
  <link href=" {% static "assets/vendor/icofont/icofont.min.css" %}" rel="stylesheet">
  <link href=" {% static "assets/vendor/boxicons/css/boxicons.min.css" %}" rel="stylesheet">
  <link href=" {% static "assets/vendor/venobox/venobox.css" %}" rel="stylesheet">
  <link href=" {% static "assets/vendor/owl.carousel/assets/owl.carousel.min.css" %}" rel="stylesheet">
  <link href=" {% static "assets/vendor/aos/aos.css" %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href=" {% static "assets/css/style.css" %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container-fluid d-flex">

      <div class="logo mr-auto">
        <!--<h1 class="text-light"><a href="index.html"><span>Ninestars</span></a></h1>-->
        <!-- Uncomment below if you prefer to use an image logo -->
         <a href="/"><img src=" {% static "logseblak.png" %}" alt="" class="img-fluid"></a>
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="/">Home</a></li>
          <li><a href="/#about">Tentang Kami</a></li>
          <li><a href="/#produk">Produk</a></li>
          <li><a href="/#contact">Kontak</a></li>

        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Daftar Outlet Seblak Bloom</h2>
          <ol>
            <li><a href="/">Home</a></li>
            <li>Daftar Outlet Seblak Bloom</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs Section -->
<div class="container-fluid p-0">
            <div class="raisa content_center">
              <h2 class="text-center mx-auto " style="color: #ffff;">Daftar Outlet Seblak Bloom</h2>
          </div>
        </div>
    <section class="inner-page">
        
      <div class="container">

         <ul class="list-group">

    {% for kota in kotas %}
    <li class="list-group-item"><h3>{{kota.nama_kota}} - <span class="label {% if kota.status == 'Tersedia' %}label-info {% else %} label-closed {% endif %}">{{kota.status}}</span></h3>
    {% for outlet in kota.outlet_set.all %}
    {{forloop.counter}}. {{outlet.alamat}}
    <br>
    {% endfor %}
    {% endfor %}</ul>
      </div>
    </section>

  </main><!-- End #main -->

   <!-- ======= Footer ======= -->
   <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact" data-aos="fade-up" data-aos-delay="100">
              <img src="logseblak.png" alt="" width="50%" class="img-fluid">
              <h3>Bloom Indonesia</h3>
           
            <p>
              Perum Ketapang Indah D3 No. 74, Jalan Suparjo Rustam, Dusun III, Sokaraja Kulon, Kec. Banyumas, Kabupaten Banyumas, Jawa Tengah 53181, Indonesia
               <br>
              <strong>Telepon:</strong> <a href="tel:+6281225570100">+6281225570100</a><br>
              <strong>Email:</strong> bloomindonesia@yahoo.co.id<br>
            </p>
          </div>


          <div class="col-lg-3 col-md-6 footer-links" data-aos="fade-up" data-aos-delay="400">
            <h4>Our Social Networks</h4>
            <p>Temukan kami di platform lainnya</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright 2020,<strong><span> Bloom Indonesia</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
      
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src=" {% static "assets/vendor/jquery/jquery.min.js" %}"></script>
  <script src=" {% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  <script src=" {% static "assets/vendor/jquery.easing/jquery.easing.min.js" %}"></script>
  <script src=" {% static "assets/vendor/php-email-form/validate.js" %}"></script>
  <script src=" {% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}"></script>
  <script src=" {% static "assets/vendor/venobox/venobox.min.js" %}"></script>
  <script src=" {% static "assets/vendor/owl.carousel/owl.carousel.min.js" %}"></script>
  <script src=" {% static "assets/vendor/aos/aos.js" %}"></script>

  <!-- Template Main JS File -->
  <script src=" {% static "assets/js/main.js" %}"></script>

</body>

</html>